### ISSUE TITLE
Add integration testing

### ISSUE THREAD

**Issue by irux** [bakdata/kpops#374] opened 2023-10-18 10:38 UTC
We should add integration tests in kpops. I think it is absolutely necessary to spin up a kafka cluster, run some pipelines and then see if the topology was deployed successfully. In that way we can decrease the risk of merging something broke inside master when we merge PRs that sometimes can be quite big.

**Comment by raminqaf** [comment] 2023-10-20 12:09
Duplicate of #16

**Closed by raminqaf** 2023-10-20 12:09 UTC
